import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    background:{
        top:0,
        backgroundColor:'#151F28'
    },
    logo:{
        height:200,
        width:200,
        left:80,
        position:"relative"
    },
    img:{
        height:200,
        width:200,
        left:80,
        position:"relative"
    },
    burgerMenu:{
        justifyContent:"flex-start",
    },
    header:{
        flexDirection:"row",
        top:10,
        left:10
    },
    address:{
        paddingBottom:15
    },
    addressText:{
        color:'#15f4ee',
        fontSize:25,
        textAlign:"center"
    },
    balance:{
        backgroundColor:'#487840',
        opacity:0.7,
        borderTopRightRadius:25,
        borderTopLeftRadius:25,
        borderBottomLeftRadius:25,
        borderBottomRightRadius:25
    },
    balanceText:{
        color:'#15f4ee',
        fontSize:25,
        textAlign:"center"
    },
    menuBoxHeader:{
        paddingTop:15,
        paddingBottom:15
    },
    menuBox:{
        backgroundColor:'#487840',
        opacity:0.7,
        alignItems:"center",
        borderTopRightRadius:25,
        borderTopLeftRadius:25,
        width:'100%'
    },
    menuImage:{
        height:32,
        width:32
    },
    menuText:{
        color:'#15f4ee',
        fontSize:25,
        paddingRight:15,
        paddingLeft:15,
    },
    thirdRow:{
        paddingBottom:15
    },
    Row:{
        flexDirection:'row'
    },
    btn:{
        top:25,
        width:150,
        alignSelf:"center",
        alignContent:"center"
    },
    bottomTabsComponent:{
        alignItems:"center",
        alignContent:"center",
        paddingTop:125,
        opacity:0.7,
        position:"relative",
    },
    otherTabs:{
        color:'#15f4ee'
    },
    highlitedTabs:{
        color:'#EEFFFF'
    },
    emptyComponent:{
        backgroundColor:'#487840',
        borderTopLeftRadius:25,
        borderTopRightRadius:25
    },
    spacing:{
        paddingLeft:0,
    },
    circleClass:{
        borderRadius:100/2,
        borderWidth:2,
        borderColor:'#15f4ee',
        left:1,
    },
    circleClassHighlited:{
        borderRadius:100/2,
        borderWidth:2,
        borderColor:'#EEFFFF',
        left:1,
    },
})

export default styles